import type { AuditEvent, MoneyMovement, OperationTrace } from './types'

export const handoverEvent: AuditEvent = {
  id: 'event-1',
  createdAt: '2026-10-04T15:30:12.000Z',
  action: 'INCOME_UPDATED',
  actionLabel: 'Ingreso modificado',
  category: 'DINERO',
  categoryLabel: 'Dinero y caja',
  entity: 'ingresos',
  entityId: 'income-1',
  subject: {
    title: 'Ingreso: SEÑA',
    detail: 'Seña Honda Wave · Juan Pérez',
    amount: '150000.5',
    operationId: 'operation-1',
    operationNumber: '120',
  },
  restricted: false,
  metadata: { amount: '150000.5', handoverTo: 'Lucas' },
  previousData: { amount: '120000', handoverTo: 'Lucas' },
  ipAddress: '10.0.0.1',
  actor: {
    id: 'user-2',
    email: 'carla@luma.test',
    name: 'Carla Caja',
    role: 'Administrativa',
  },
  branch: { id: 'branch-1', code: 'SM', name: 'San Miguel' },
}

export const cashMovement: MoneyMovement = {
  id: 'movement-1',
  createdAt: '2026-10-04T15:30:12.000Z',
  occurredAt: '2026-10-04T03:00:00.000Z',
  account: {
    id: 'account-1',
    code: 'EF',
    name: 'Caja Lucas',
    type: 'SOCIO',
    currency: 'ARS',
  },
  branch: null,
  type: 'INGRESO',
  direction: 'CREDITO',
  amount: '150000.5',
  reference: null,
  notes: null,
  registeredBy: { id: 'p-1', fullName: 'Vera Vendedora' },
  source: { kind: 'INCOME', id: 'income-1', title: 'SEÑA · Seña Honda Wave' },
  client: 'Juan Pérez',
  operation: { id: 'operation-1', number: '120', client: 'Juan Pérez' },
  paymentMethod: 'EFECTIVO',
  handover: {
    to: { id: 'p-2', fullName: 'Lucas' },
    status: 'RENDIDO',
    confirmedAt: '2026-10-04T18:00:00.000Z',
    confirmedBy: { id: 'p-2', fullName: 'Lucas' },
  },
  reversalOfId: null,
  reversal: null,
}

export const operationTrace: OperationTrace = {
  operation: {
    id: 'operation-1',
    number: '120',
    ticketNumber: 'B-77',
    date: '2026-10-01T03:00:00.000Z',
    status: 'APROBADA',
    deliveryStatus: 'PENDIENTE',
    deliveredAt: null,
    client: 'Juan Pérez',
    vehicle: 'Wave 110',
    vin: null,
    branch: { id: 'branch-1', code: 'SM', name: 'San Miguel' },
    listPrice: '2000000',
    minimumPrice: '1900000',
    agreedPrice: '1850000',
    createdBy: { id: 'p-1', fullName: 'Vera Vendedora' },
    createdAt: '2026-10-01T14:00:00.000Z',
    updatedAt: '2026-10-02T14:00:00.000Z',
  },
  approvals: [
    {
      id: 'approval-1',
      decision: 'APROBADA',
      requestedBy: { id: 'p-1', fullName: 'Vera Vendedora' },
      requestedAt: '2026-10-01T14:05:00.000Z',
      decidedBy: { id: 'p-9', fullName: 'Gerardo Gerente' },
      decidedAt: '2026-10-01T16:20:00.000Z',
      listPrice: '2000000',
      minimumPrice: '1900000',
      agreedPrice: '1850000',
      reason: 'Cliente frecuente',
    },
  ],
  events: [handoverEvent],
  eventsTotal: 1,
  movements: [cashMovement],
}
